version: 2
jobs:
  build:
    working_directory: ~/convus/convus_webapp
    parallelism: 2
    shell: /bin/bash --login
    environment:
      RAILS_ENV: test
      RACK_ENV: test
    docker:
      - image: circleci/ruby:3.0.2-node
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:12.1-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: convus_test
      - image: redis:4.0.9
    steps:
      - checkout
      - restore_cache:
          keys:
            # This branch if available
            - v3-dep-{{ .Branch }}-
            # Default branch if not
            - v3-dep-main-
            # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
            - v3-dep-
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: install system libraries
          command: sudo apt-get update && sudo apt-get -y install imagemagick postgresql-client
      - run:
          name: install bundler
          command: gem install bundler
      - run:
          name: bundle gems
          command: bundle install --path=vendor/bundle --jobs=4 --retry=3
      # So that we can compile assets, since we use node & yarn
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
      - run:
          name: "Assets: precompile"
          command: |
            set -x
            node --version
            bin/webpack
            bundle exec rails assets:precompile assets:clean --trace
      - run:
          name: Wait for PostgreSQL to start
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - save_cache:
          key: v3-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - ./vendor/bundle
            - ~/.bundle
            - public/assets
            - tmp/cache/assets/sprockets
            - ~/.cache/yarn
      - run:
          name: Setup Database
          command: |
            bundle exec rails db:create db:schema:load
      - run:
          name: Rspec tests
          command: |
            mkdir -p test-results/rspec test-artifacts
            TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec --profile 10 \
                              --color \
                              --order random \
                              --format RspecJunitFormatter \
                              --out test-results/rspec/rspec.xml \
                              --format progress \
                              -- ${TESTFILES}
      - run:
          name: Jest Tests
          command: |
            mkdir -p test-results/junit
            yarn test --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: "test-results/junit/"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-artifacts

  deploy_production:
    machine:
      enabled: true
    working_directory: ~/convus/convus_webapp
    steps:
      - checkout
      - run:
          name: Deploying to Cloud66 Production
          command: |
            curl -X POST -d "" https://hooks.cloud66.com/stacks/redeploy/${CLOUD66_REDEPLOYMENT_PATH}

workflows:
  version: 2
  commit:
    jobs:
      - build
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: main
